package br.edu.ifpb.iftech.lolcadora.exceptions;

public enum ProblemKey {
    LOGIN_EXISTENTE,
    USUARIO_NAO_ENCONTRADO,
    USUARIO_NAO_AUTORIZADO,
    USUARIO_NAO_AUTENTICADO,

    FILME_JA_CADASTRADO,
    FILME_NAO_ENCONTRADO,
    GENERO_NAO_ENCONTRADO,

    REQUISICAO_INVALIDA,
    ARGUMENTO_INVALIDO,
    REQUISICAO_ILEGIVEL,
    ERRO_DESCONHECIDO,
    ERRO_CONCORRENCIA
}
